.gitmodules
=> feat: submodule 연결

.gitmodules, src/main/java/com/deundeunhaku/reliablekkuserver/common/config/S3Configuration.java, src/main/java/com/deundeunhaku/reliablekkuserver/s3/dto/S3Response.java, src/main/java/com/deundeunhaku/reliablekkuserver/s3/service/S3UploadService.java, src/main/resources/application.yaml
=> feat: AWS S3 연결 컴포넌트 구현

src/docs/asciidoc/index.adoc, src/docs/asciidoc/member-login-register.adoc, src/main/java/com/deundeunhaku/reliablekkuserver/common/exception/LoginFailedException.java, src/main/java/com/deundeunhaku/reliablekkuserver/jwt/JwtController.java, src/main/java/com/deundeunhaku/reliablekkuserver/jwt/constants/TokenDuration.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/controller/MemberAuthenticationController.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/dto/LoginRequest.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/repository/MemberRepository.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/service/MemberService.java, src/main/resources/application.yaml, src/main/resources/static/docs/index.html, src/main/resources/static/docs/member-login-register.html, src/test/java/com/deundeunhaku/reliablekkuserver/BaseControllerTest.java, src/test/java/com/deundeunhaku/reliablekkuserver/BaseDisplayNameConfig.java, src/test/java/com/deundeunhaku/reliablekkuserver/BaseRepositoryTest.java, src/test/java/com/deundeunhaku/reliablekkuserver/BaseServiceTest.java, src/test/java/com/deundeunhaku/reliablekkuserver/config/TestConfig.java, src/test/java/com/deundeunhaku/reliablekkuserver/member/controller/MemberAuthenticationControllerTest.java, src/test/java/com/deundeunhaku/reliablekkuserver/member/service/MemberServiceTest.java
SER-3
- test에 사용할 기본 클래스 구현 
- 로그인 api 구현
=> feat: 로그인 api 구현

src/docs/asciidoc/member-login-register.adoc, src/main/java/com/deundeunhaku/reliablekkuserver/member/controller/MemberAuthenticationController.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/controller/MemberRegisterController.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/domain/CertificationNumber.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/dto/MemberRegisterRequest.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/dto/PhoneNumberRequest.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/repository/CertificationNumberRepository.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/service/MemberService.java, src/main/java/com/deundeunhaku/reliablekkuserver/sms/constant/SmsConstant.java, src/main/java/com/deundeunhaku/reliablekkuserver/sms/dto/RecipientList.java, src/main/java/com/deundeunhaku/reliablekkuserver/sms/dto/SmsCertificationNumber.java, src/main/java/com/deundeunhaku/reliablekkuserver/sms/dto/SmsResponse.java, src/main/java/com/deundeunhaku/reliablekkuserver/sms/dto/ToSmsServerRequest.java, src/main/java/com/deundeunhaku/reliablekkuserver/sms/service/SmsService.java, src/main/resources/application.yaml, src/main/resources/static/docs/member-login-register.html, src/test/java/com/deundeunhaku/reliablekkuserver/member/controller/MemberRegisterControllerTest.java, src/test/java/com/deundeunhaku/reliablekkuserver/member/service/MemberServiceTest.java
SER-5
- sms 전송 로직 구현 
- 회원가입, 휴대전화 인증, 중복확인, 인증번호 확인 api 구현
=> feat: 회원가입 관련 api 구현

src/docs/asciidoc/member-login-register.adoc, src/main/java/com/deundeunhaku/reliablekkuserver/member/controller/MemberFindPasswordController.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/domain/Member.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/dto/FindPasswordRequest.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/service/MemberService.java, src/main/java/com/deundeunhaku/reliablekkuserver/sms/service/SmsService.java, src/main/resources/static/docs/member-login-register.html, src/test/java/com/deundeunhaku/reliablekkuserver/member/controller/MemberFindPasswordControllerTest.java
인증번호 전송, 확인, 새 비밀번호 전화번호로 보내기
SER-6
- 비밀번호 찾기 관련 api 구현 (인증번호 전송, 확인, 새 비밀번호 전화번호로 보내기)
=> feat: 비밀번호 찾기 관련 api 구현

src/docs/asciidoc/admin-order.adoc, src/docs/asciidoc/index.adoc, src/main/java/com/deundeunhaku/reliablekkuserver/member/domain/OfflineMember.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/repository/OfflineMemberRepository.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/controller/OfflineOrderController.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/domain/Order.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/dto/OfflineOrderRequest.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/service/OrderService.java, src/main/resources/static/docs/admin-order.html, src/test/java/com/deundeunhaku/reliablekkuserver/order/controller/OfflineOrderControllerTest.java
=> feat: 오프라인 주문 로직 구현

src/docs/asciidoc/admin-order.adoc, src/main/java/com/deundeunhaku/reliablekkuserver/order/controller/AdminOrderController.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/domain/Order.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/service/AdminOrderService.java, src/main/resources/static/docs/admin-order.html, src/test/java/com/deundeunhaku/reliablekkuserver/order/controller/AdminOrderControllerTest.java
=> feat: 관리자 주문 접수 api 구현

src/docs/asciidoc/admin-store.adoc, src/docs/asciidoc/index.adoc, src/docs/asciidoc/store.adoc, src/main/java/com/deundeunhaku/reliablekkuserver/store/constant/STORE_ID.java, src/main/java/com/deundeunhaku/reliablekkuserver/store/controller/AdminStoreController.java, src/main/java/com/deundeunhaku/reliablekkuserver/store/controller/StoreController.java, src/main/java/com/deundeunhaku/reliablekkuserver/store/domain/Store.java, src/main/java/com/deundeunhaku/reliablekkuserver/store/repository/StoreRepository.java, src/main/java/com/deundeunhaku/reliablekkuserver/store/service/StoreService.java, src/main/resources/application-local.yaml, src/main/resources/static/docs/admin-store.html, src/main/resources/static/docs/store.html, src/test/java/com/deundeunhaku/reliablekkuserver/store/controller/AdminStoreControllerTest.java, src/test/java/com/deundeunhaku/reliablekkuserver/store/controller/StoreControllerTest.java
=> feat: 가게  영업 시작 , 종료 로직 구현

src/main/java/com/deundeunhaku/reliablekkuserver/menu/dto/MenuResponse.java, src/main/resources/static/docs/admin-order.html, src/main/resources/static/docs/admin-store.html, src/main/resources/static/docs/index.html, src/main/resources/static/docs/member-login-register.html, src/main/resources/static/docs/menu.html, src/main/resources/static/docs/order.html, src/main/resources/static/docs/store.html, src/test/java/com/deundeunhaku/reliablekkuserver/menu/controller/MenuControllerTest.java
SER-30
- 사용자 메뉴 가져오는 api 설명 컬럼 빠져서 추가
=> fix: 사용자 메뉴 가져오는 api 설명 컬럼 빠져서 추가

src/docs/asciidoc/mypage.adoc, src/main/java/com/deundeunhaku/reliablekkuserver/member/controller/MemberWithdrawController.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/domain/Member.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/service/MemberService.java, src/main/resources/static/docs/member-login-register.html, src/main/resources/static/docs/mypage.html, src/test/java/com/deundeunhaku/reliablekkuserver/member/controller/MemberWithdrawControllerTest.java, src/test/java/com/deundeunhaku/reliablekkuserver/member/service/MemberServiceTest.java
=> feat: 사용자 회원탈퇴 api 구현

src/docs/asciidoc/mypage.adoc, src/main/java/com/deundeunhaku/reliablekkuserver/member/controller/MemberMyPageController.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/domain/Member.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/dto/MemberMyPageResponse.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/service/MemberService.java, src/main/resources/static/docs/member-login-register.html, src/main/resources/static/docs/mypage.html, src/test/java/com/deundeunhaku/reliablekkuserver/member/controller/MemberMyPageControllerTest.java, src/test/java/com/deundeunhaku/reliablekkuserver/member/service/MemberServiceTest.java
ex) SER-36
feat: 사용자 마이페이지 회원 정보(이름, 레벨) api 구현
=> feat: 사용자 마이페이지 회원 정보(이름, 레벨) api 구현

src/docs/asciidoc/admin-member.adoc, src/docs/asciidoc/index.adoc, src/main/java/com/deundeunhaku/reliablekkuserver/member/controller/AdminMemberController.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/dto/AdminMemberManagementResponse.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/repository/MemberRepository.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/repository/MemberRepositoryCustom.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/repository/MemberRepositoryImpl.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/service/AdminMemberService.java, src/main/resources/static/docs/admin-login.html, src/main/resources/static/docs/admin-member.html, src/main/resources/static/docs/index.html, src/main/resources/static/docs/member-login-register.html, src/test/java/com/deundeunhaku/reliablekkuserver/member/controller/AdminMemberControllerTest.java, src/test/java/com/deundeunhaku/reliablekkuserver/order/controller/OrderControllerTest.java
=> feat: 어드민 회원관리 api 구현

src/docs/asciidoc/mypage.adoc, src/main/java/com/deundeunhaku/reliablekkuserver/order/controller/OrderController.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/dto/OrderCalendarResponse.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/repository/OrderRepository.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/service/OrderService.java, src/main/resources/static/docs/member-login-register.html, src/main/resources/static/docs/mypage.html, src/test/java/com/deundeunhaku/reliablekkuserver/order/controller/OrderControllerTest.java, src/test/java/com/deundeunhaku/reliablekkuserver/order/service/OrderServiceTest.java
ex) SER-26
feat: 마이페이지 캘린더 api 구현
=> feat: 마이페이지 캘린더 api 구현

src/docs/asciidoc/admin-menu.adoc, src/docs/asciidoc/index.adoc, src/main/java/com/deundeunhaku/reliablekkuserver/menu/controller/AdminMenuController.java, src/main/java/com/deundeunhaku/reliablekkuserver/menu/domain/Menu.java, src/main/java/com/deundeunhaku/reliablekkuserver/menu/dto/AdminMenuChangeResponse.java, src/main/java/com/deundeunhaku/reliablekkuserver/menu/repository/AdminMenuRepository.java, src/main/java/com/deundeunhaku/reliablekkuserver/menu/service/AdminMenuService.java, src/main/resources/static/docs/admin-login.html, src/main/resources/static/docs/admin-member.html, src/main/resources/static/docs/index.html, src/main/resources/static/docs/member-login-register.html, src/main/resources/static/docs/mypage.html, src/test/java/com/deundeunhaku/reliablekkuserver/ReliableKkuServerApplicationTests.java, src/test/java/com/deundeunhaku/reliablekkuserver/menu/controller/AdminMenuControllerTest.java
SER-17
- 관리자 메뉴 리스트 api 및 관리자 품절, 품절헤제 api 구현
=> feat: 관리자 메뉴 리스트 api 및 관리자 품절, 품절헤제 api 구현

src/docs/asciidoc/admin-menu.adoc, src/docs/asciidoc/mypage.adoc, src/main/java/com/deundeunhaku/reliablekkuserver/menu/controller/AdminCreateMenuController.java, src/main/java/com/deundeunhaku/reliablekkuserver/menu/controller/AdminMenuController.java, src/main/java/com/deundeunhaku/reliablekkuserver/menu/domain/Menu.java, src/main/java/com/deundeunhaku/reliablekkuserver/menu/dto/CreateMenuRequest.java, src/main/java/com/deundeunhaku/reliablekkuserver/menu/dto/CreateMenuResponse.java, src/main/java/com/deundeunhaku/reliablekkuserver/menu/repository/AdminMenuRepository.java, src/main/java/com/deundeunhaku/reliablekkuserver/menu/service/AdminCreateMenuService.java, src/main/java/com/deundeunhaku/reliablekkuserver/menu/service/AdminMenuService.java, src/main/resources/static/docs/admin-login.html, src/main/resources/static/docs/admin-member.html, src/main/resources/static/docs/admin-order.html, src/main/resources/static/docs/admin-store.html, src/main/resources/static/docs/index.html, src/main/resources/static/docs/member-login-register.html, src/main/resources/static/docs/menu.html, src/main/resources/static/docs/mypage.html, src/main/resources/static/docs/order.html, src/main/resources/static/docs/store.html, src/test/java/com/deundeunhaku/reliablekkuserver/menu/controller/AdminCreateMenuControllerTest.java, src/test/java/com/deundeunhaku/reliablekkuserver/menu/controller/AdminMenuControllerTest.java, src/test/java/com/deundeunhaku/reliablekkuserver/menu/service/AdminCreateMenuServiceTest.java, src/test/java/com/deundeunhaku/reliablekkuserver/menu/service/AdminMenuServiceTest.java
SER-18
feat: 관리자 메뉴 추가, 삭제 api 구현
=> feat: 관리자 메뉴 추가, 삭제 api 구현

src/docs/asciidoc/admin-order.adoc, src/main/java/com/deundeunhaku/reliablekkuserver/jwt/JwtController.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/controller/AdminAuthenticationController.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/controller/MemberAuthenticationController.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/constant/OrderStatus.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/controller/AdminOrderController.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/controller/OrderController.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/controller/OrderSseController.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/service/AdminOrderService.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/service/OrderService.java, src/main/java/com/deundeunhaku/reliablekkuserver/sse/dto/SseDataResponse.java, src/main/java/com/deundeunhaku/reliablekkuserver/sse/service/SseService.java, src/main/resources/static/docs/admin-login.html, src/main/resources/static/docs/admin-member.html, src/main/resources/static/docs/admin-order.html, src/main/resources/static/docs/member-login-register.html, src/test/java/com/deundeunhaku/reliablekkuserver/order/controller/AdminOrderControllerTest.java, src/test/java/com/deundeunhaku/reliablekkuserver/order/controller/OrderControllerTest.java
SER-24
- 관리자 주문,제작,픽업,완료,미수령,복구 api 구현
=> feat: 관리자 주문,제작,픽업,완료,미수령,복구 api 구현 

Dockerfile-dev, Dockerfile-local, Dockerfile-prod
SER-39
- feat: Dockerfile 추가 (local, dev, prod)
=> feat: Dockerfile 추가 (local, dev, prod)

src/docs/asciidoc/order.adoc, src/main/java/com/deundeunhaku/reliablekkuserver/order/controller/OrderController.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/dto/LeftTimeResponse.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/repository/OrderRepository.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/service/OrderService.java, src/main/resources/static/docs/admin-login.html, src/main/resources/static/docs/admin-member.html, src/main/resources/static/docs/member-login-register.html, src/main/resources/static/docs/order.html, src/main/resources/static/docs/token.html, src/test/java/com/deundeunhaku/reliablekkuserver/order/controller/OrderControllerTest.java
SER-40
- 마지막 주문의 예상 남은 시간에 10분을 더해서 반환
=> feat: 현재 주문하면 대략적으로 걸리는 시간을 반환하는 api 구현

src/main/java/com/deundeunhaku/reliablekkuserver/member/domain/CertificationNumber.java, src/main/java/com/deundeunhaku/reliablekkuserver/member/domain/Member.java, src/main/java/com/deundeunhaku/reliablekkuserver/menu/domain/Menu.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/domain/Order.java, src/main/java/com/deundeunhaku/reliablekkuserver/payment/domain/Payment.java, src/main/resources/application-dev.yaml, src/main/resources/application-prod.yaml
SER-41
- aws rds 연결 및 데이터베이스 generate-ddl 시 에러안나게 수정
=> feat: aws rds 연결 및 데이터베이스 generate-ddl 시 에러안나게 수정

src/main/java/com/deundeunhaku/reliablekkuserver/payment/dto/PaymentCancelDataResponse.java
ex) SER-21
fix: PaymentCancelDataResponse Number -> Integer로 수정
=> fix: PaymentCancelDataResponse Number -> Integer로 수정

src/docs/asciidoc/admin-login.adoc, src/docs/asciidoc/admin-order.adoc, src/main/java/com/deundeunhaku/reliablekkuserver/order/controller/AdminOrderController.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/dto/OrderEachCountResponse.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/repository/OrderRepositoryCustom.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/repository/OrderRepositoryImpl.java, src/main/java/com/deundeunhaku/reliablekkuserver/order/service/AdminOrderService.java, src/main/resources/static/docs/admin-login.html, src/main/resources/static/docs/admin-order.html, src/test/java/com/deundeunhaku/reliablekkuserver/order/controller/AdminOrderControllerTest.java, src/test/java/com/deundeunhaku/reliablekkuserver/order/service/AdminOrderServiceTest.java
SER-44
관리자 매출 상태별 주문 개수 조회 api 구현
=> feat: 관리자 매출 상태별 주문 개수 조회 api 구현
